1-8 requested improvements
ALMaclaine/tag-manager pull request #4
Opened 2021-01-23 08:46 UTC by lauras5

issues #3 
- also changed some func names

2021-01-23 18:44 UTC, ALMaclaine requested changes

2021-01-23 18:44 UTC, ALMaclaine commented on client/src/TagComponent.svelte
> +    import { deleteTag } from 'sql-tag-system-fetch-utils';
This should be split into two components.

TagList/TagView
Tag

Don't put Component in the name

2021-01-23 18:44 UTC, ALMaclaine commented on client/src/TagComponent.svelte
> +              <Icon class="myClass1 myClass2" icon={faTimes}></Icon>
what are these classes

2021-01-23 18:44 UTC, ALMaclaine commented on client/src/TagComponent.svelte
> +        <span class="ml-4 bg-gray-300 rounded-full w-6 h-6 flex justify-center items-center leading-6" on:click={handleDelete(id)}>
Mmm i dont think that click handler should work, its run on creation you need a arrow function () => handleDelete

2021-01-23 18:44 UTC, ALMaclaine commented on client/src/App.svelte
> +    let limit = 100;
Unless this is changed in the UI it shouldn't be a global variable, it's only used in the handleAddMoreFunction

2021-01-23 18:44 UTC, ALMaclaine commented on client/src/App.svelte
>      let page = 0;
same with page

2021-01-23 18:44 UTC, ALMaclaine commented on client/package.json
> +    "fa-svelte": "^3.1.0",
Is this for sure a dev dep? Is that in the docs? Have you tried building and seeing if it works outside of dev?

2021-01-23 20:12 UTC, lauras5 commented on client/src/TagComponent.svelte
> +              <Icon class="myClass1 myClass2" icon={faTimes}></Icon>
- removed classes

2021-01-23 20:12 UTC, lauras5 commented on client/src/TagComponent.svelte
> +        <span class="ml-4 bg-gray-300 rounded-full w-6 h-6 flex justify-center items-center leading-6" on:click={handleDelete(id)}>
updated to arrow function

2021-01-23 20:43 UTC, lauras5 commented on client/package.json
> +    "fa-svelte": "^3.1.0",
- docs say to install as dev dependency, works outside on build too

2021-01-23 20:44 UTC, lauras5 commented on client/src/App.svelte
>      let page = 0;
moved to handleAddMore function, i was unsure if we needed to edit values in the future

2021-01-24 03:08 UTC, ALMaclaine approved these changes
lgtm

2021-01-24 03:08 UTC, ALMaclaine commented
closes #3

2021-01-24 03:08 UTC, merged

2021-01-24 03:09 UTC, ALMaclaine commented
closes #3